"""Change type and name of column text

Revision ID: e59117be9c6d
Revises: bd021304033d
Create Date: 2026-05-24 21:44:53.836383

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e59117be9c6d"
down_revision: Union[str, Sequence[str], None] = "bd021304033d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "articles", sa.Column("tex_file", sa.LargeBinary(), nullable=True)
    )
    op.drop_column("articles", "text")
    op.alter_column(
        "preview_images",
        "image",
        existing_type=postgresql.BYTEA(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "preview_images",
        "image",
        existing_type=postgresql.BYTEA(),
        nullable=False,
    )
    op.add_column(
        "articles",
        sa.Column("text", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_column("articles", "tex_file")
    # ### end Alembic commands ###
