"""Change name of column

Revision ID: 7c609dee3717
Revises: e59117be9c6d
Create Date: 2026-05-28 22:34:13.507491

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7c609dee3717"
down_revision: Union[str, Sequence[str], None] = "e59117be9c6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("articles", sa.Column("mdx", sa.Text(), nullable=True))
    op.drop_column("articles", "tex_file")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "articles",
        sa.Column(
            "tex_file", postgresql.BYTEA(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("articles", "mdx")
    # ### end Alembic commands ###
