"""Add some additional columns to article image table

Revision ID: 362e0f1e6770
Revises: 2bbf74104b30
Create Date: 2026-05-30 14:17:58.990425

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "362e0f1e6770"
down_revision: Union[str, Sequence[str], None] = "2bbf74104b30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "article_images", sa.Column("height", sa.Integer(), nullable=True)
    )
    op.add_column(
        "article_images", sa.Column("width", sa.Integer(), nullable=True)
    )
    op.add_column(
        "article_images", sa.Column("caption", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("article_images", "caption")
    op.drop_column("article_images", "width")
    op.drop_column("article_images", "height")
    # ### end Alembic commands ###
