user  root;
worker_processes  1;

# Store PID in /tmp (always writable)
pid /tmp/nginx.pid;

events {
}

http {
    server {
        listen       80;
        server_name  localhost;

        # Root directory where React.js build files are placed
        root /usr/share/nginx/html;
        index index.html;

        # Serve React.js static files with proper caching
        location / {
            proxy_pass http://frontend:3000/;
        }

        # Serve React.js static files with proper caching
        location /api/ {
            proxy_pass http://backend:8000/;
        }
    }
}