user  root;
worker_processes  1;

# Store PID in /tmp (always writable)
pid /tmp/nginx.pid;

events {
}

http {

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen       80;
        server_name  localhost;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri /index.html;
        }

        location /api/ {
            proxy_pass http://backend:8000/;
        }
    }
}