/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LlmRouteImport } from './routes/llm'
import { Route as LiveRouteImport } from './routes/live'
import { Route as DlRouteImport } from './routes/dl'
import { Route as DevRouteImport } from './routes/dev'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MlIndexRouteImport } from './routes/ml/index'
import { Route as MlRouteRouteImport } from './routes/ml/$route'

const LlmRoute = LlmRouteImport.update({
  id: '/llm',
  path: '/llm',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const DlRoute = DlRouteImport.update({
  id: '/dl',
  path: '/dl',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MlIndexRoute = MlIndexRouteImport.update({
  id: '/ml/',
  path: '/ml/',
  getParentRoute: () => rootRouteImport,
} as any)
const MlRouteRoute = MlRouteRouteImport.update({
  id: '/ml/$route',
  path: '/ml/$route',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dev': typeof DevRoute
  '/dl': typeof DlRoute
  '/live': typeof LiveRoute
  '/llm': typeof LlmRoute
  '/ml/$route': typeof MlRouteRoute
  '/ml/': typeof MlIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dev': typeof DevRoute
  '/dl': typeof DlRoute
  '/live': typeof LiveRoute
  '/llm': typeof LlmRoute
  '/ml/$route': typeof MlRouteRoute
  '/ml': typeof MlIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dev': typeof DevRoute
  '/dl': typeof DlRoute
  '/live': typeof LiveRoute
  '/llm': typeof LlmRoute
  '/ml/$route': typeof MlRouteRoute
  '/ml/': typeof MlIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dev'
    | '/dl'
    | '/live'
    | '/llm'
    | '/ml/$route'
    | '/ml/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/dev' | '/dl' | '/live' | '/llm' | '/ml/$route' | '/ml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dev'
    | '/dl'
    | '/live'
    | '/llm'
    | '/ml/$route'
    | '/ml/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DevRoute: typeof DevRoute
  DlRoute: typeof DlRoute
  LiveRoute: typeof LiveRoute
  LlmRoute: typeof LlmRoute
  MlRouteRoute: typeof MlRouteRoute
  MlIndexRoute: typeof MlIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/llm': {
      id: '/llm'
      path: '/llm'
      fullPath: '/llm'
      preLoaderRoute: typeof LlmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dl': {
      id: '/dl'
      path: '/dl'
      fullPath: '/dl'
      preLoaderRoute: typeof DlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ml/': {
      id: '/ml/'
      path: '/ml'
      fullPath: '/ml/'
      preLoaderRoute: typeof MlIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ml/$route': {
      id: '/ml/$route'
      path: '/ml/$route'
      fullPath: '/ml/$route'
      preLoaderRoute: typeof MlRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DevRoute: DevRoute,
  DlRoute: DlRoute,
  LiveRoute: LiveRoute,
  LlmRoute: LlmRoute,
  MlRouteRoute: MlRouteRoute,
  MlIndexRoute: MlIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
